name = "QuantumStateDistributions"
uuid = "78ba9c6e-4c92-4abc-8d32-e9cb1304b8da"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.2.0"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuantumStateBase = "73ce9c4f-35d1-4161-b9e6-26915895bfed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ClassicalOrthogonalPolynomials = "0.5"
Distributions = "0.25"
ProgressMeter = "1.7"
QuantumStateBase = "1.2"
julia = "1.6"

[extras]
QuantumStateBase = "73ce9c4f-35d1-4161-b9e6-26915895bfed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "QuantumStateBase"]
