name = "QuantumStateDistributions"
uuid = "78ba9c6e-4c92-4abc-8d32-e9cb1304b8da"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
QuantumStateBase = "73ce9c4f-35d1-4161-b9e6-26915895bfed"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
